# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c11c5c022637b7c5508ad4977dd32d1d6b543859487ef92129c5b06dbb87641d4c0e99962af505069206dab56ce03f979bf6a8428a36c2ceaafb0b0a81c8d951

test:
  secret_key_base: 2f660e14fa112987bee6828d428887064d7283bffa43636b83aa9ce3bdaa0fe4202ecc043e6d1c4457cdc143ca6a56361ae36fe454569376ac4987c1b106f8dc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
